```{r include=FALSE}
install.packages("Quandl")
library(Quandl)
install.packages("dplyr")
library(dplyr)
install.packages("readr")
library(readr)
install.packages("utils")
library(utils)
library(pacman)
pacman::p_load("fredr")

if(set_eval){
  knitr::opts_chunk$set(echo=FALSE, fig.keep='high', out.width = '95%', fig.align = 'center', warning = FALSE, message = FALSE, results = "asis", root.dir = "C:/Users/user/OneDrive/Rstudio/API_Rstudio/AgEconnomics/Ag production") 
}
  
if(!set_eval){
  knitr::opts_chunk$set(echo=FALSE, fig.keep='high', out.width = '95%', fig.align = 'center', warning = FALSE, message = FALSE, results = "asis", eval = FALSE, root.dir = "C:/Users/user/OneDrive/Rstudio/API_Rstudio/AgEconnomics/Ag production") 
} 

```


The data are accessible through the web using the link `https://fccfac.sharepoint.com/sites/AgEconomics/DATA/Ag production/Name_of_file`, where `Name_of_file` includes the `.csv` extension. You need enter your FCC credential to access the data.

## Futures


### Corn

- `Corn futures - daily.csv`: US futures corn price the price in USD per bushel for the front month downloaded from Quandl;

```{r corn_futures, results = "hide"}

#if(Sys.time() - file.info("Corn futures - daily.csv")$mtime > weeks(1) & pingr::is_online()){
  
  # Corn futures - front month
  corn_d <- Quandl("CHRIS/CME_C1") 
  
  # corn_m <- corn_d %>%
  #   mutate(date = as.Date(Date),
  #          corn_futures = Settle,
  #          month = month(date),
  #          year = year(date)) %>%
  #   dplyr::select(year, month, corn_futures) %>%
  #   group_by(year, month) %>%
  #   summarize(corn_futures = mean(corn_futures)) %>%
  #   ungroup() %>%
  #   mutate(date = as.Date(paste(year, month, "01", sep = "-")),
  #          Price = corn_futures/100) %>%
  #   dplyr::select(date, Price) %>%
  #   arrange(desc(date))
  
  # CSV files
  corn_d <- corn_d %>%
    mutate(date = as.Date(Date),
           price = Settle/100) %>%
    dplyr::select(date, price)
  
  write_csv(corn_d, "C:/Users/user/OneDrive/Rstudio/API_Rstudio/AgEconnomics/Ag production/Corn futures - daily.csv")
  
#}

```
